<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require_once 'phpmailer/Exception.php';
require_once 'phpmailer/PHPMailer.php';
require_once 'phpmailer/SMTP.php';

function sendRoutingAlert($toEmail, $routingTitle, $daysWithoutUpdate)
{
    $mail = new PHPMailer(true);

    try {
        $mail->isSMTP();
        $mail->Host = 'smtp.gmail.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'Smiletech4edLab@taytayrizal.gov.ph';
        $mail->Password = 'odml cajk cfil hqah';
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail->Port = 587;

        $mail->setFrom('Smiletech4edLab@taytayrizal.gov.ph', 'Municipal Education Office System');
        $mail->addAddress($toEmail);

        $mail->isHTML(true);
        $mail->Subject = '[SMILE System] Action Required: Delayed Routing Document Notice';
        $mail->Body = '
            <div style="font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif; background-color: #f0f4f8; padding: 30px; color: #333333;">
                <div style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.08);">
                    
                    <!-- Header with SMILE Branding -->
                    <div style="background: linear-gradient(135deg, #0d6efd 0%, #0043a8 100%); color: #ffffff; padding: 25px; text-align: center;">
                        <h1 style="margin: 0; font-size: 22px; letter-spacing: 0.5px;">Municipal Education Office System</h1>
                        <p style="margin: 6px 0 0; font-size: 13px; opacity: 0.85; text-transform: uppercase; letter-spacing: 1px;">Automated Document Tracking & Management</p>
                    </div>
                    
                    <!-- Main Body Content -->
                    <div style="padding: 35px 30px;">
                        <h3 style="color: #c92a2a; margin-top: 0; font-size: 18px; border-bottom: 2px solid #ffc9c9; padding-bottom: 8px;">⚠️ Pending Document Notice</h3>
                        
                        <p style="font-size: 15px; line-height: 1.6; color: #495057;">
                            Greetings,
                        </p>
                        <p style="font-size: 15px; line-height: 1.6; color: #495057;">
                            Please be advised that the routing document specified below has exceeded the standard processing timeframe without any recent updates:
                        </p>
                        
                        <!-- Highlight Info Box -->
                        <div style="background-color: #f8f9fa; border-left: 4px solid #c92a2a; padding: 18px; margin: 25px 0; border-radius: 6px;">
                            <p style="margin: 0 0 10px; font-size: 14px; color: #212529;"><strong>Document Title / Tracking:</strong> <span style="color: #0d6efd;">' . $routingTitle . '</span></p>
                            <p style="margin: 0; font-size: 14px; color: #212529;"><strong>Inactive Duration:</strong> <span style="color: #c92a2a; font-weight: bold;">' . $daysWithoutUpdate . ' days</span> without update</p>
                        </div>
                        
                        <p style="font-size: 14px; color: #495057; line-height: 1.6;">
                            Kindly log in to the system to review, process, or update its status immediately to prevent unnecessary delays in workflow.
                        </p>
                        
                        <!-- Call to Action Button -->
                        <div style="text-align: center; margin-top: 30px;">
                            <a href="http://localhost/Stti/routing.php" style="background-color: #0d6efd; color: #ffffff; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 14px; display: inline-block; box-shadow: 0 3px 6px rgba(13, 110, 253, 0.3);">Open SMILE System</a>
                        </div>
                    </div>
                    
                    <!-- Footer -->
                    <div style="background-color: #e9ecef; padding: 15px 20px; text-align: center; font-size: 12px; color: #6c757d; border-top: 1px solid #dee2e6;">
                        <p style="margin: 0;">This is an automated notification generated by the <strong>Municipal Education Office System</strong>. Please do not reply directly to this email.</p>
                    </div>
                    
                </div>
            </div>
        ';

        $mail->send();
        return true;
    } catch (Exception $e) {
        return false;
    }
}
?>